const MX_STATES = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Coahuila',
  'Colima',
  'Durango',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'México',
  'Michoacán',
  'Morelos',
  'Nayarit',
  'Nuevo León',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana Roo',
  'San Luis Potosí',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatán',
  'Zacatecas',
  'Ciudad de México',
];

const MX_STATE_ABBREVIATIONS = {
  Aguascalientes: 'AGU',
  'Baja California': 'BCN',
  'Baja California Sur': 'BCS',
  Campeche: 'CAM',
  Chiapas: 'CHIS',
  Chihuahua: 'CHIH',
  Coahuila: 'COAH',
  Colima: 'COL',
  Durango: 'DGO',
  Guanajuato: 'GTO',
  Guerrero: 'GRO',
  Hidalgo: 'HGO',
  Jalisco: 'JAL',
  México: 'MEX',
  Michoacán: 'MIC',
  Morelos: 'MOR',
  Nayarit: 'NAY',
  'Nuevo León': 'NL',
  Oaxaca: 'OAX',
  Puebla: 'PUE',
  Querétaro: 'QRO',
  'Quintana Roo': 'QROO',
  'San Luis Potosí': 'SLP',
  Sinaloa: 'SIN',
  Sonora: 'SON',
  Tabasco: 'TAB',
  Tamaulipas: 'TAM',
  Tlaxcala: 'TLAX',
  Veracruz: 'VER',
  Yucatán: 'YUC',
  Zacatecas: 'ZAC',
  'Ciudad de México': 'CDMX',
};

const MX_STATE_CAPITALS = {
  Aguascalientes: 'Aguascalientes',
  'Baja California': 'Mexicali',
  'Baja California Sur': 'La Paz',
  Campeche: 'Campeche',
  Chiapas: 'Tuxtla Gutiérrez',
  Chihuahua: 'Chihuahua',
  Coahuila: 'Saltillo',
  Colima: 'Colima',
  Durango: 'Durango',
  Guanajuato: 'Guanajuato',
  Guerrero: 'Chilpancingo',
  Hidalgo: 'Pachuca',
  Jalisco: 'Guadalajara',
  México: 'Toluca',
  Michoacán: 'Morelia',
  Morelos: 'Cuernavaca',
  Nayarit: 'Tepic',
  'Nuevo León': 'Monterrey',
  Oaxaca: 'Oaxaca',
  Puebla: 'Puebla',
  Querétaro: 'Querétaro',
  'Quintana Roo': 'Chetumal',
  'San Luis Potosí': 'San Luis Potosí',
  Sinaloa: 'Culiacán',
  Sonora: 'Hermosillo',
  Tabasco: 'Villahermosa',
  Tamaulipas: 'Ciudad Victoria',
  Tlaxcala: 'Tlaxcala',
  Veracruz: 'Xalapa',
  Yucatán: 'Mérida',
  Zacatecas: 'Zacatecas',
  'Ciudad de México': 'Ciudad de México',
};

const MX_STATE_NEIGHBORS = {
  Aguascalientes: ['Zacatecas', 'Jalisco'],
  'Baja California': ['Sonora', 'Baja California Sur'],
  'Baja California Sur': ['Baja California'],
  Campeche: ['Yucatán', 'Quintana Roo', 'Tabasco'],
  Chiapas: ['Tabasco', 'Veracruz', 'Oaxaca'],
  Chihuahua: ['Sonora', 'Sinaloa', 'Durango', 'Coahuila'],
  Coahuila: [
    'Chihuahua',
    'Durango',
    'Zacatecas',
    'Nuevo León',
    'San Luis Potosí',
  ],
  Colima: ['Jalisco', 'Michoacán'],
  Durango: ['Chihuahua', 'Sinaloa', 'Nayarit', 'Zacatecas', 'Coahuila'],
  Guanajuato: [
    'Jalisco',
    'Zacatecas',
    'San Luis Potosí',
    'Querétaro',
    'Michoacán',
  ],
  Guerrero: ['Michoacán', 'México', 'Morelos', 'Puebla', 'Oaxaca'],
  Hidalgo: [
    'San Luis Potosí',
    'Querétaro',
    'México',
    'Tlaxcala',
    'Puebla',
    'Veracruz',
  ],
  Jalisco: [
    'Nayarit',
    'Zacatecas',
    'Aguascalientes',
    'Guanajuato',
    'Michoacán',
    'Colima',
  ],
  México: [
    'Querétaro',
    'Hidalgo',
    'Tlaxcala',
    'Puebla',
    'Morelos',
    'Guerrero',
    'Michoacán',
  ],
  Michoacán: ['Colima', 'Jalisco', 'Guanajuato', 'México', 'Guerrero'],
  Morelos: ['México', 'Guerrero', 'Puebla'],
  Nayarit: ['Sinaloa', 'Durango', 'Zacatecas', 'Jalisco'],
  'Nuevo León': ['Coahuila', 'Tamaulipas', 'San Luis Potosí'],
  Oaxaca: ['Guerrero', 'Puebla', 'Veracruz', 'Chiapas'],
  Puebla: [
    'Tlaxcala',
    'México',
    'Guerrero',
    'Oaxaca',
    'Veracruz',
    'Hidalgo',
    'Morelos',
  ],
  Querétaro: ['San Luis Potosí', 'Guanajuato', 'México', 'Hidalgo'],
  'Quintana Roo': ['Yucatán', 'Campeche'],
  'San Luis Potosí': [
    'Zacatecas',
    'Coahuila',
    'Nuevo León',
    'Tamaulipas',
    'Veracruz',
    'Hidalgo',
    'Querétaro',
    'Guanajuato',
  ],
  Sinaloa: ['Sonora', 'Chihuahua', 'Durango', 'Nayarit'],
  Sonora: ['Chihuahua', 'Sinaloa', 'Baja California'],
  Tabasco: ['Campeche', 'Veracruz', 'Chiapas'],
  Tamaulipas: ['Nuevo León', 'San Luis Potosí', 'Veracruz'],
  Tlaxcala: ['Puebla', 'México', 'Hidalgo'],
  Veracruz: [
    'Tamaulipas',
    'San Luis Potosí',
    'Hidalgo',
    'Puebla',
    'Oaxaca',
    'Tabasco',
  ],
  Yucatán: ['Campeche', 'Quintana Roo'],
  Zacatecas: [
    'Durango',
    'Coahuila',
    'San Luis Potosí',
    'Guanajuato',
    'Aguascalientes',
    'Jalisco',
    'Nayarit',
  ],
  'Ciudad de México': ['México'],
};

const MX_STATE_NAME_MAP = {
  Aguascalientes: 'Aguascalientes',
  'Baja California': 'Baja California',
  'Baja California Sur': 'Baja California Sur',
  Campeche: 'Campeche',
  Chiapas: 'Chiapas',
  Chihuahua: 'Chihuahua',
  Coahuila: 'Coahuila',
  Colima: 'Colima',
  Durango: 'Durango',
  Guanajuato: 'Guanajuato',
  Guerrero: 'Guerrero',
  Hidalgo: 'Hidalgo',
  Jalisco: 'Jalisco',
  México: 'México',
  Michoacán: 'Michoacán',
  Morelos: 'Morelos',
  Nayarit: 'Nayarit',
  'Nuevo León': 'Nuevo León',
  Oaxaca: 'Oaxaca',
  Puebla: 'Puebla',
  Querétaro: 'Querétaro',
  'Quintana Roo': 'Quintana Roo',
  'San Luis Potosí': 'San Luis Potosí',
  Sinaloa: 'Sinaloa',
  Sonora: 'Sonora',
  Tabasco: 'Tabasco',
  Tamaulipas: 'Tamaulipas',
  Tlaxcala: 'Tlaxcala',
  Veracruz: 'Veracruz',
  Yucatán: 'Yucatán',
  Zacatecas: 'Zacatecas',
  'Ciudad de México': 'Ciudad de México',
  'Mexico City': 'Ciudad de México',
};

const GEOJSON_URL_MX =
  'https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/mexico.geojson';

export {
  MX_STATES,
  MX_STATE_ABBREVIATIONS,
  MX_STATE_CAPITALS,
  MX_STATE_NEIGHBORS,
  MX_STATE_NAME_MAP,
  GEOJSON_URL_MX,
};
