const US_STATE_ABBREVIATIONS = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  Florida: 'FL',
  Georgia: 'GA',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Pennsylvania: 'PA',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
  'District of Columbia': 'DC',
};

const US_STATE_CAPITALS = {
  Alabama: 'Montgomery',
  Alaska: 'Juneau',
  Arizona: 'Phoenix',
  Arkansas: 'Little Rock',
  California: 'Sacramento',
  Colorado: 'Denver',
  Connecticut: 'Hartford',
  Delaware: 'Dover',
  Florida: 'Tallahassee',
  Georgia: 'Atlanta',
  Hawaii: 'Honolulu',
  Idaho: 'Boise',
  Illinois: 'Springfield',
  Indiana: 'Indianapolis',
  Iowa: 'Des Moines',
  Kansas: 'Topeka',
  Kentucky: 'Frankfort',
  Louisiana: 'Baton Rouge',
  Maine: 'Augusta',
  Maryland: 'Annapolis',
  Massachusetts: 'Boston',
  Michigan: 'Lansing',
  Minnesota: 'Saint Paul',
  Mississippi: 'Jackson',
  Missouri: 'Jefferson City',
  Montana: 'Helena',
  Nebraska: 'Lincoln',
  Nevada: 'Carson City',
  'New Hampshire': 'Concord',
  'New Jersey': 'Trenton',
  'New Mexico': 'Santa Fe',
  'New York': 'Albany',
  'North Carolina': 'Raleigh',
  'North Dakota': 'Bismarck',
  Ohio: 'Columbus',
  Oklahoma: 'Oklahoma City',
  Oregon: 'Salem',
  Pennsylvania: 'Harrisburg',
  'Rhode Island': 'Providence',
  'South Carolina': 'Columbia',
  'South Dakota': 'Pierre',
  Tennessee: 'Nashville',
  Texas: 'Austin',
  Utah: 'Salt Lake City',
  Vermont: 'Montpelier',
  Virginia: 'Richmond',
  Washington: 'Olympia',
  'West Virginia': 'Charleston',
  Wisconsin: 'Madison',
  Wyoming: 'Cheyenne',
  'District of Columbia': 'Washington, D.C.',
};

const US_STATE_NEIGHBORS = {
  Alabama: ['Florida', 'Georgia', 'Tennessee', 'Mississippi'],
  Alaska: [],
  Arizona: ['California', 'Nevada', 'Utah', 'New Mexico'],
  Arkansas: [
    'Missouri',
    'Tennessee',
    'Mississippi',
    'Louisiana',
    'Texas',
    'Oklahoma',
  ],
  California: ['Oregon', 'Nevada', 'Arizona'],
  Colorado: ['Wyoming', 'Nebraska', 'Kansas', 'Oklahoma', 'New Mexico', 'Utah'],
  Connecticut: ['Massachusetts', 'Rhode Island', 'New York'],
  Delaware: ['Maryland', 'Pennsylvania', 'New Jersey'],
  Florida: ['Alabama', 'Georgia'],
  Georgia: [
    'Florida',
    'Alabama',
    'Tennessee',
    'North Carolina',
    'South Carolina',
  ],
  Hawaii: [],
  Idaho: ['Washington', 'Oregon', 'Nevada', 'Utah', 'Wyoming', 'Montana'],
  Illinois: ['Wisconsin', 'Indiana', 'Kentucky', 'Missouri', 'Iowa'],
  Indiana: ['Michigan', 'Ohio', 'Kentucky', 'Illinois'],
  Iowa: [
    'Minnesota',
    'Wisconsin',
    'Illinois',
    'Missouri',
    'Nebraska',
    'South Dakota',
  ],
  Kansas: ['Nebraska', 'Missouri', 'Oklahoma', 'Colorado'],
  Kentucky: [
    'Indiana',
    'Ohio',
    'West Virginia',
    'Virginia',
    'Tennessee',
    'Missouri',
    'Illinois',
  ],
  Louisiana: ['Arkansas', 'Mississippi', 'Texas'],
  Maine: ['New Hampshire'],
  Maryland: ['Pennsylvania', 'Delaware', 'Virginia', 'West Virginia'],
  Massachusetts: [
    'Vermont',
    'New Hampshire',
    'Rhode Island',
    'Connecticut',
    'New York',
  ],
  Michigan: ['Wisconsin', 'Indiana', 'Ohio'],
  Minnesota: ['Wisconsin', 'Iowa', 'South Dakota', 'North Dakota'],
  Mississippi: ['Tennessee', 'Alabama', 'Louisiana', 'Arkansas'],
  Missouri: [
    'Iowa',
    'Illinois',
    'Kentucky',
    'Tennessee',
    'Arkansas',
    'Oklahoma',
    'Kansas',
    'Nebraska',
  ],
  Montana: ['Idaho', 'Wyoming', 'South Dakota', 'North Dakota'],
  Nebraska: [
    'South Dakota',
    'Iowa',
    'Missouri',
    'Kansas',
    'Colorado',
    'Wyoming',
  ],
  Nevada: ['Oregon', 'Idaho', 'Utah', 'Arizona', 'California'],
  'New Hampshire': ['Maine', 'Massachusetts', 'Vermont'],
  'New Jersey': ['New York', 'Pennsylvania', 'Delaware'],
  'New Mexico': ['Colorado', 'Oklahoma', 'Texas', 'Arizona'],
  'New York': [
    'Vermont',
    'Massachusetts',
    'Connecticut',
    'New Jersey',
    'Pennsylvania',
  ],
  'North Carolina': ['Virginia', 'Tennessee', 'Georgia', 'South Carolina'],
  'North Dakota': ['Minnesota', 'South Dakota', 'Montana'],
  Ohio: ['Michigan', 'Indiana', 'Kentucky', 'West Virginia', 'Pennsylvania'],
  Oklahoma: [
    'Kansas',
    'Missouri',
    'Arkansas',
    'Texas',
    'New Mexico',
    'Colorado',
  ],
  Oregon: ['Washington', 'Idaho', 'Nevada', 'California'],
  Pennsylvania: [
    'New York',
    'New Jersey',
    'Delaware',
    'Maryland',
    'West Virginia',
    'Ohio',
  ],
  'Rhode Island': ['Massachusetts', 'Connecticut'],
  'South Carolina': ['North Carolina', 'Georgia'],
  'South Dakota': [
    'North Dakota',
    'Minnesota',
    'Iowa',
    'Nebraska',
    'Wyoming',
    'Montana',
  ],
  Tennessee: [
    'Kentucky',
    'Virginia',
    'North Carolina',
    'Georgia',
    'Alabama',
    'Mississippi',
    'Arkansas',
    'Missouri',
  ],
  Texas: ['Oklahoma', 'Arkansas', 'Louisiana', 'New Mexico'],
  Utah: ['Idaho', 'Wyoming', 'Colorado', 'Arizona', 'Nevada'],
  Vermont: ['New Hampshire', 'Massachusetts', 'New York'],
  Virginia: [
    'Maryland',
    'West Virginia',
    'Kentucky',
    'Tennessee',
    'North Carolina',
  ],
  Washington: ['Idaho', 'Oregon'],
  'West Virginia': ['Pennsylvania', 'Maryland', 'Virginia', 'Kentucky', 'Ohio'],
  Wisconsin: ['Michigan', 'Minnesota', 'Iowa', 'Illinois'],
  Wyoming: ['Montana', 'South Dakota', 'Nebraska', 'Colorado', 'Utah', 'Idaho'],
};

const GEOJSON_URL_US =
  'https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json';

export {
  US_STATE_ABBREVIATIONS,
  US_STATE_CAPITALS,
  US_STATE_NEIGHBORS,
  GEOJSON_URL_US,
};
